name: example
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  string_literal_finder_annotations:
    path: ../../string_literal_finder_annotations
  logger: ^1.0.0
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.17.9
